---
id: Auth
name: Auth
full: Authentication and user management library
description: >-
  A library that provides a common interface into various authentication
  backends.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Auth
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha6
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/exception: ^3
      horde/translation: ^3
      horde/util: ^3
    ext:
      hash: '*'
  optional:
    composer:
      horde/db: ^3
      horde/history: ^3
      horde/lock: ^3
      horde/imap_client: ^3
      horde/kolab_session: ^3
      horde/ldap: ^3
      horde/imsp: ^3
      horde/http: ^3
      horde/test: ^3
    ext:
      ctype: '*'
      ftp: '*'
      pam: '*'
      sasl: '*'
